### ISSUE TITLE
phone number isn't working

### ISSUE THREAD

**Issue by rsbxDev** [oSumAtrIX/marcophono-premium#2]
When I try to call a mobile number with it, it says "This is a mobile number!
Calls to mobile networks are expensive, so Marcophono can only enable them if you have a premium account."
Could you try to make it possible to call mobile numbers again?

**Comment by mori0** [comment]
I also wanted to ask whether it is also possible to make mobile phone numbers callable

**Comment by oSumAtrIX** [comment]
No, calls are handled server-sided.
